export default [
    {
        "continent": "Europe",
        "continent-iso": "EU",
        "country": "Austria",
        "country-iso": "AT",
        "region": "Upper Austria",
        "region-iso": "AT-4",
        "city": "Linz",
        "apdex": 1.00,
        "useractions": 0.45,
        "errors": 0.06,
        "loadactions": 0.68,
        "totaluseractions": 17,
        "affecteduseractions": 29.41
    },
    {
        "continent": "Europe",
        "continent-iso": "EU",
        "country": "Austria",
        "country-iso": "AT",
        "region": "Upper Austria",
        "region-iso": "AT-4",
        "city": "Wels",
        "apdex": 0.60,
        "useractions": 0.30,
        "errors": 0.06,
        "loadactions": 0.68,
        "totaluseractions": 17,
        "affecteduseractions": 29.41
    },
    {
        "continent": "Europe",
        "continent-iso": "EU",
        "country": "Austria",
        "country-iso": "AT",
        "apdex": 0.89,
        "useractions": 0.75,
        "errors": 0.03,
        "loadactions": 0.78,
        "totaluseractions": 28,
        "affecteduseractions": 1.02
    },
    {
        "continent": "Europe",
        "continent-iso": "EU",
        "country": "Germany",
        "country-iso": "DE",
        "apdex": 0.46,
        "useractions": 0.20,
        "errors": 0.08,
        "loadactions": 0.90,
        "totaluseractions": 66,
        "affecteduseractions": 36.45
    },
    {
        "continent": "North America",
        "continent-iso": "NA",
        "country": "United States",
        "country-iso": "US",
        "region": "New York",
        "region-iso": "US-NY",
        "city": "New York City",
        "apdex": 0.91,
        "useractions": 0.66,
        "errors": 0.09,
        "loadactions": 0.98,
        "totaluseractions": 55,
        "affecteduseractions": 35.07
    },
    {
        "continent": "Europe",
        "continent-iso": "EU",
        "country": "Germany",
        "country-iso": "DE",
        "region": "Berlin",
        "region-iso": "DE-BE",
        "city": "Berlin",
        "apdex": 0.81,
        "useractions": 0.81,
        "errors": 0.08,
        "loadactions": 0.77,
        "totaluseractions": 11,
        "affecteduseractions": 55.6
    },
    {
        "continent": "Europe",
        "continent-iso": "EU",
        "country": "Great Britain",
        "country-iso": "GB",
        "region": "Scotland",
        "region-iso": "GB-SCT",
        "apdex": 0.68,
        "useractions": 0.66,
        "errors": 0.08,
        "loadactions": 0.98,
        "totaluseractions": 25,
        "affecteduseractions": 13.41
    },
    {
        "continent": "Europe",
        "continent-iso": "EU",
        "country": "Spain",
        "country-iso": "ES",
        "apdex": 0.23,
        "useractions": 0.23,
        "errors": 0.18,
        "loadactions": 0.60,
        "totaluseractions": 11,
        "affecteduseractions": 36.66
    },
    {
        "continent": "Europe",
        "continent-iso": "EU",
        "country": "Norway",
        "country-iso": "NO",
        "apdex": 0.21,
        "useractions": 0.18,
        "errors": 0.17,
        "loadactions": 0.60,
        "totaluseractions": 11,
        "affecteduseractions": 36.66
    }
]